Implementação da classe NN, Dense, Sigmoid_Activation, SoftMaxActivation e ReLUActivation no sub-package neural_networks.

In [1]:
# -*- coding: utf-8 -*-

# modules
import sys
import numpy as np
sys.path.insert(0, 'C:/Users/ASUS/Desktop/Bioinfo/2ano/Sistemas Inteligentes/si/src/si')

from data.dataset import Dataset
from neural_networks.nn import NN
from neural_networks.layers import Dense, Sigmoid_Activation, SoftMaxActivation, ReLUActivation, LinearActivation


## NN test

In [2]:
# dataset

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([1, 0, 0, 1])
dataset = Dataset(X, y, features = ['x1', 'x2'], label = ['AND', 'OR'])

In [3]:
l1 = Dense(input_size=2, output_size=2)
l2 = Dense(input_size=2, output_size=1)

l1_seq = Sigmoid_Activation()
l2_seq = Sigmoid_Activation()

layers = [l1, l1_seq, l2, l2_seq]
nn_model = NN(layers)  

In [4]:
nn_model.fit(dataset)

In [5]:
nn_model.predict(dataset)

array([[0.49968838],
       [0.49969368],
       [0.49968866],
       [0.49969395]])

## 10.3 - Binary problem

In [6]:
# training dataset
n_examples = 120
n_features = 32

np.random.seed(32)
X = np.random.randn(n_examples, n_features)
y = np.random.randint(0, 2, n_examples)

dataset_bin = Dataset(X, y)
dataset_bin.y

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0])

In [7]:
l1 = Dense(input_size=32, output_size=32)
l2 = Dense(input_size=32, output_size=32//2)
l3 = Dense(input_size=32//2, output_size=1)

l1_seq = Sigmoid_Activation()
l2_seq = Sigmoid_Activation()
l3_seq = Sigmoid_Activation()

layers = [l1, l1_seq, l2, l2_seq, l3, l3_seq]
nn_model_bin = NN(layers)  

In [ ]:
nn_model_bin.fit(dataset_bin)

In [ ]:
nn_model_bin.predict(dataset_bin)

## 10.4 - Multiclass problem

In [10]:
# training dataset
n_examples = 120
n_features = 32

np.random.seed(32)
X = np.random.randn(n_examples, n_features)
y = np.random.randint(0, 3, n_examples)

dataset_mult = Dataset(X, y)
dataset_mult.y

array([2, 2, 2, 2, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 0, 2, 1, 1, 1, 1, 0,
       1, 2, 2, 0, 0, 0, 1, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 1, 2, 1, 2, 0,
       2, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 1,
       2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 2])

In [11]:
l1 = Dense(input_size=32, output_size=32)
l2 = Dense(input_size=32, output_size=32//2)
l3 = Dense(input_size=32//2, output_size=3)

l1_seq = Sigmoid_Activation()
l2_seq = Sigmoid_Activation()
l3_soft = SoftMaxActivation()

layers = [l1, l1_seq, l2, l2_seq, l3, l3_soft]
nn_model_mult = NN(layers)  

In [ ]:
nn_model_mult.fit(dataset_mult)

In [ ]:
nn_model_mult.predict(dataset_mult)

## 10.5 - Regression problem

In [13]:
# training dataset
n_examples = 120
n_features = 32

np.random.seed(32)
X = np.random.randn(n_examples, n_features)
y = np.random.randn(n_examples)

dataset_reg = Dataset(X, y)

In [14]:
l1 = Dense(input_size=32, output_size=32)
l2 = Dense(input_size=32, output_size=32//2)
l3 = Dense(input_size=32//2, output_size=1)

l1_relu = ReLUActivation()
l2_relu = ReLUActivation()
l3_lin = LinearActivation()


layers = [l1, l1_relu, l2, l2_relu, l3, l3_lin]
nn_model_reg = NN(layers)  

In [ ]:
nn_model_reg.fit(dataset_reg)

In [ ]:
nn_model_reg.predict(dataset_reg)